### ISSUE TITLE
Sonar cloud not working

### ISSUE THREAD

**Issue by alu0100785630** [ULL-ESIT-INF-DSI-2021/ull-esit-inf-dsi-20-21-prct09-async-fs-process-alu0100785630#1]
Me fallan el github action de Sonar Cloud. Cambié la rama main a master en la configuración, no se si tiene algo que ver. 
Me he dado cuenta de que tampoco se generan .nyc_output y coverage al hacer el push.

Podría ayudarme? Gracias :) @esegredo @amarrerod

**Comment by esegredo** [comment]
Hola @alu0100785630 ,

Te recomiendo que leas este hilo para que pruebes las diferentes soluciones que proporcionan, porque es el error que te está emitiendo la GitHub Action de Sonar Cloud:

https://community.sonarsource.com/t/could-not-find-a-default-branch-to-fall-back-on/25095/3

Respecto al cubrimiento, si miras la ejecución de los diferentes pasos de la GitHub Action, el cubrimiento si que te genera los ficheros en el lugar apropiado (coverage/lcov.info), que es lo que luego indicas en el fichero de propiedades de Sonar Cloud, también. Aparentemente está todo bien configurado.

Una opción podría ser eliminar el proyecto de Sonar Cloud y volver a crearlo.

Ya nos cuentas.

Saludos.
